version: 1
formatters:
  console:
    format: "%(asctime)s - %(levelname)s - %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
  common:
    format: "%(asctime)s - %(levelname)s - %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
handlers:
  console:
    class : logging.StreamHandler
    formatter: console
    level   : INFO
    stream  : ext://sys.stdout
  # 不同会输出大于等于此级别的信息。
  common:
    class: logging.handlers.RotatingFileHandler
    formatter: common
    level: INFO
    maxBytes: 10240000
    encoding: utf8
    filename: "logs/main.log"
    # 日志保留个数
    backupCount: 5
loggers:
  main.common:
    level: INFO
    handlers: [common]
root:
  level: DEBUG
  handlers: [console]